# Numpy practice

finished by crD

Get familiar with Numpy. A relatively systematic way to practice Numpy

Study guide link:

[Numpy Tutorial Part 1 – Introduction to Arrays](https://www.machinelearningplus.com/python/numpy-tutorial-part1-array-python-examples/)

[Numpy Tutorial Part 2 – Vital Functions for Data Analysis](https://www.machinelearningplus.com/python/numpy-tutorial-python-part2/)

[101 NumPy Exercises for Data Analysis (Python)](https://www.machinelearningplus.com/python/101-numpy-exercises-python/)

So let's begin!

In [1]:
import numpy as np

## Numpy Turorial Part 1

In [6]:
# Create a list (1-d array)
list1 = [1, 2, 3, 4]
np_list1 = np.array(list1)

print(type(np_list1))
print(np_list1)
print(np_list1.shape)

<class 'numpy.ndarray'>
[1 2 3 4]
(4,)


In [3]:
# NP array broadcasting
# list1_ADD2 = list1 + 2  # This causes an error

np_list1_ADD2 = np_list1 + 2
print(np_list1)
print(np_list1_ADD2)


[1 2 3 4]
[3 4 5 6]


In [12]:
# Create a matrix (2-d array)

list2 = [[0, 2, 3], [4, 5, 6], [7, 8, 9]]
np_list2 = np.array(list2)

print(type(np_list2))
print(np_list2)
print(np_list2.shape)


<class 'numpy.ndarray'>
[[0 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [18]:
# Change the data type
np_list2_float = np.array(list2, dtype = 'float')

print(type(np_list2_float))
print(np_list2_float)
print(np_list2_float.shape)

print()

# Boolean conversion (0 -> False, else -> 1)
np_list2_bool = np.array(list2, dtype = 'bool')
print(np_list2_bool)

<class 'numpy.ndarray'>
[[ 0.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]
(3, 3)

[[False  True  True]
 [ True  True  True]
 [ True  True  True]]


In [19]:
# convert type 
np_list2_int = np_list2_float.astype('int')
np_list2_str = np_list2_float.astype('str')

print(np_list2_int)
print(np_list2_str)

[[0 2 3]
 [4 5 6]
 [7 8 9]]
[['0.0' '2.0' '3.0']
 ['4.0' '5.0' '6.0']
 ['7.0' '8.0' '9.0']]


In [21]:
# Some information access: shape, dtype， size and ndim

print('Shape: ', np_list2.shape)
print('Data type: ', np_list2.dtype)
print('Size: ', np_list2.size)
print('Number of dimensions: ', np_list2.ndim)

Shape:  (3, 3)
Data type:  int64
Size:  9
Number of dimensions:  2


In [25]:
# Extract items from nd-array
print(np_list2)
print()
print(np_list2[:2, :2]) # Not include 2
print(np_list2[1:, 1:]) # include 1

[[0 2 3]
 [4 5 6]
 [7 8 9]]

[[0 2]
 [4 5]]
[[5 6]
 [8 9]]


In [40]:
# Boolean output
print(np_list2)
print()

b = np_list2 >= 5
print(b)

print()
print(np_list2[b])

[[0 2 3]
 [4 5 6]
 [7 8 9]]

[[False False False]
 [False  True  True]
 [ True  True  True]]

[5 6 7 8 9]


In [31]:
# Reverse elements

# randomly generate integers given upper bound and size
np_list3 = np.random.randint(10, size = (4, 4))
print(np_list3)

np_list3_r = np_list3[::-1, :]
print()
print(np_list3_r)

[[2 2 6 7]
 [2 3 1 2]
 [8 6 8 1]
 [6 6 3 9]]

[[6 6 3 9]
 [8 6 8 1]
 [2 3 1 2]
 [2 2 6 7]]


In [38]:
# inf and nan

np_list3_float = np_list3.astype('float')
np_list3_float[0, 0] = np.inf
np_list3_float[1, 1] = np.nan
print(np_list3_float)

[[ inf   2.   6.   7.]
 [  2.  nan   1.   2.]
 [  8.   6.   8.   1.]
 [  6.   6.   3.   9.]]
